---
- name: demo the paths
  hosts: localhost
  gather_facts: False

  tasks:
      - name: demo basename
        debug:
            msg: "{{ '/var/log/nova/nova-api.log' | basename }}"
      - name: demo dirname
        debug:
            msg: "{{ '/var/log/nova/nova-api.log' | dirname }}"
      - name: demo expanduser
        debug:
            msg: "{{ '~/.stackrc' | expanduser }}"
