---
- name: demo the template
  hosts: localhost
  gather_facts: False
  vars:
    api:
        v2: False

  tasks:
      - name: pause with render
        debug:
            msg: "API = cinder{{ 'v2' if api.v2 else '' }}"
