---
- name: demo filters
  hosts: localhost
  gather_facts: False

  vars:
      num1: 10
      num3: 10
  tasks:

      - name: string methods
        debug:
            msg: "{{ 'foo bar baz'.upper().split() }}"
      - name: logic comparison
        debug:
            msg: "Can you read me?"
        when: num1 >= num3 and num1 is even and num2 is not defined
