# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
   
  config.vm.define "vagrant1" do |vagrant1|
    config.vm.box = "generic/ubuntu1804"
    config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", guest: 443, host:8443, host_ip: "127.0.0.1"
  end
  config.vm.define "vagrant2" do |vagrant2|
    config.vm.box = "generic/ubuntu1804"
    config.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", guest: 443, host:8444, host_ip: "127.0.0.1"
  end
  config.vm.define "vagrant3" do |vagrant3|
    config.vm.box = "generic/ubuntu1804"
    config.vm.network "forwarded_port", guest: 80, host: 8082, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", guest: 443, host:8445, host_ip: "127.0.0.1"
  end

end
